### ISSUE TITLE
Skipping in agentCounter

### ISSUE THREAD

**Issue by ebgolden** [kefik/Pogamut3#40]
https://github.com/kefik/Pogamut3/blob/aef5e20524d0ff1d5ed1fb66b9c20dda8c74c494/Main/PogamutBase/src/main/java/cz/cuni/amis/pogamut/base/agent/impl/AgentId.java#L66

In the case that the host is unknown, the agentCounter is iterated twice (once in try and once in catch), so agentCounter will skip an iteration. A simple fix would be to iterate agentCounter once at the beginning of the method (before the try/catch) instead of iterating it in both the try and catch.

```java
public AgentId(@Named(AGENT_NAME_DEPENDENCY) String agentName) {
    NullCheck.check(agentName, "name");
    UUID uuid = null;
    ++agentCounter;
    try {
        synchronized(random) {
            uuid = new UUID(random.nextLong(), random.nextLong());
        }
        this.token = Tokens.get(agentName + "-" + (agentCounter) + "@"
        + InetAddress.getLocalHost().getCanonicalHostName() + "/" + uuid.toString());
    } catch (UnknownHostException ex) {
        this.token = Tokens.get(getClass().getSimpleName() + "-" + (agentCounter) + "@unknownHost/" + uuid.toString());
    }
    getName().setFlag(agentName);
}
```

**Comment by kefik** [comment]
Fixed and pushed into the repo. Thanks!

**Comment by ebgolden** [comment]
Np!

**Comment by kefik** [comment]
Out of curiosity, how have you heard about Pogamut and what is the occasion reading AgentId class code?

**Comment by ebgolden** [comment]
Certainly! I'm reading a dissertation on RL in FPS games. The author used
Pogamut and I started looking into the workings of the library. If you're
interested, here is a link to the dissertation:


https://www.researchgate.net/profile/Didula-Sa/publication/344280825_Adaptive_Agent_for_FPS_Games_using_Reinforcement_Learning/links/5f63057c4585154dbbd74cbb/Adaptive-Agent-for-FPS-Games-using-Reinforcement-Learning.pdf
